{
 "title": "Builds Oveview",
 "description": "OpenShift Bulds State",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div align=\"center\">\n  <H1>Red Hat Summit Lab Cluster - Builds Overview</H1>\n</div>"
  },
  {
   "title": "Running Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(openshift_build_active_time_seconds{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pending Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(openshift_build_active_time_seconds{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Build Erros",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openshift_build_total{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Completed Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openshift_build_total{phase=\"Complete\"})"
    }
   ]
  }
 ]
}