{
 "title": "Cluster's Nodes Status",
 "description": "Dashboard to get an overview of one server",
 "tags": [
  "openshift",
  "nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu{instance=~\"$server\"}))"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size{instance=~\"$server\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Scrape CPU use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_exporter_scrape_duration_seconds_sum{instance=~\"$server\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"} - node_memory_Cached{instance=~\"$server\"} - node_memory_Buffers{instance=~\"$server\"} - node_memory_Slab{instance=~\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$server\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$server\"} + node_memory_Slab{instance=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$server\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_pswpin{instance=~\"$server\"}",
     "legendFormat": "Swap In"
    },
    {
     "expr": "node_vmstat_pswpout{instance=~\"$server\"}",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "( (node_memory_MemFree{instance=~\"$server\"} + node_memory_Cached{instance=~\"$server\"} + node_memory_Slab{instance=~\"$server\"} + node_memory_Buffers{instance=~\"$server\"} ) / node_memory_MemTotal{instance=~\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Free Filesystem (Lowest)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{fstype=~\"xfs|ext4\",instance=~\"$server\"} / node_filesystem_size{fstype=~\"xfs|ext4\",instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} OUT"
    },
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$server\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} IN"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$server\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$server\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_ms{instance=~\"$server\"}[5m]))",
     "legendFormat": "io time"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$server\"}[5m])) + sum by (instance) (irate(node_disk_writes_completed{instance=~\"$server\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_read{instance=~\"$server\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_written{instance=~\"$server\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_read{instance=~\"$server\"}[5m])) + sum by (instance) (irate(node_disk_bytes_written{instance=~\"$server\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "IO time by device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "5 most used filesystems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, 100 - (node_filesystem_free{instance=~\"$server\",fstype=~\"xfs|ext4\"} / node_filesystem_size{instance=~\"$server\",fstype=~\"xfs|ext4\"} * 100))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "node_filesystem_size{instance=~\"$server\",fstype=~\"xfs|ext4\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Use per Filesystem",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free{instance=~\"$server\",fstype=~\"xfs|ext4\"} / node_filesystem_size{instance=~\"$server\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}