{
 "title": "Labs Generic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nodes Down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - up{job=\"kubernetes-nodes\"}",
     "legendFormat": "node: {{ instance }}"
    }
   ]
  },
  {
   "title": "Pod Count per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "node: {{ instance }}" }
   ]
  },
  {
   "title": "Registry Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"registry-claim\"})/1000000000",
     "legendFormat": "Available Space"
    },
    {
     "expr": "(avg(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"registry-claim\"})/1000000000) - (avg(kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"registry-claim\"})/1000000000)",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "DNS errors per node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_dnsmasq_sync_error_count_total",
     "legendFormat": "node {{ instance }}"
    }
   ]
  },
  {
   "title": "Time Drift from average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(avg(node_time{job=\"kubernetes-nodes-exporter\"})) - node_time{job=\"kubernetes-nodes-exporter\"} ",
     "legendFormat": "Node : {{ instance }}"
    }
   ]
  },
  {
   "title": "Master1 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^master1.*\"})"
    }
   ]
  },
  {
   "title": "Master2 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^master2.*\"})"
    }
   ]
  },
  {
   "title": "Master3 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^master3.*\"})"
    }
   ]
  },
  {
   "title": "average pod count per compute node",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " (sum(kubelet_running_pod_count{instance=~\"^node.*\"}) / (count(node_time) -6))"
    }
   ]
  },
  {
   "title": "Node Capacity/Available Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes-nodes\"}) * 100 / count(node_time)",
     "legendFormat": "Node Capacity"
    }
   ]
  },
  {
   "title": "Infra1 Pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^infra1.*\"})"
    }
   ]
  },
  {
   "title": "infra2 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^infra2.*\"})"
    }
   ]
  },
  {
   "title": "Infra3 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^infra3.*\"})"
    }
   ]
  },
  {
   "title": "Node1 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^node1.*\"})"
    }
   ]
  },
  {
   "title": "Node2 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^node2.*\"})"
    }
   ]
  },
  {
   "title": "Node3 pod count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum(kubelet_running_pod_count{instance=~\"^node3.*\"})"
    }
   ]
  },
  {
   "title": "POD Count Table on each node",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "kubelet_running_pod_count" }
   ]
  }
 ]
}