{
 "title": "OpenShift Cluster Monitoring",
 "description": "Monitors Openshift cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "openshift"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage ",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/docker_.*\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/mapper/docker_.*\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/docker_.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/docker_.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) ",
       "legendFormat": "overall cpu usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent", "label": "% Usage" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[16s])) by (pod_name) * 100",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Cores Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes Memory usage ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_memory_usage_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_rss{systemd_service_name=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (irate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (irate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (irate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenShift Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "openshift_build_total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "openshift_build_total" }
     ]
    },
    {
     "title": "Returns the number of builds that have been running for more than 10 minutes (600 seconds).",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(openshift_build_active_time_seconds{phase=\"running\"} < time() - 600)"
      }
     ]
    },
    {
     "title": "Returns the number of build that have been waiting at least 10 minutes (600 seconds) to start.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(openshift_build_active_time_seconds{phase=\"pending\"} < time() - 600)"
      }
     ]
    },
    {
     "title": "Returns the number of failed builds, regardless of the failure reason.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(openshift_build_total{phase=\"failed\"})"
      }
     ]
    },
    {
     "title": "Returns the number of failed builds because of problems retrieving source from the associated Git repository.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_build_total{phase=\"failed\",reason=\"fetchsourcefailed\"}"
      }
     ]
    },
    {
     "title": "Returns the number of successfully completed builds.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(openshift_build_total{phase=\"complete\"})"
      }
     ]
    },
    {
     "title": "Returns the failed builds totals, per failure reason, from 5 minutes ago.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_build_total{phase=\"failed\"} offset 5m"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenShift SDN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "openshift_sdn_pod_setup_latency_sum",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_sdn_pod_setup_latency_sum"
      }
     ]
    },
    {
     "title": "openshift_sdn_pod_teardown_latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_sdn_pod_teardown_latency"
      }
     ]
    },
    {
     "title": "openshift_sdn_pod_ips",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "openshift_sdn_pod_ips" }
     ]
    },
    {
     "title": "garbage_collector_monitoring_route:openshift:io_v1_rate_limiter_use",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "garbage_collector_monitoring_route:openshift:io_v1_rate_limiter_use"
      }
     ]
    },
    {
     "title": "openshift_sdn_arp_cache_entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_sdn_arp_cache_entries"
      }
     ]
    },
    {
     "title": "openshift_sdn_arp_cache_entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "openshift_sdn_arp_cache_entries"
      }
     ]
    },
    {
     "title": "Top 10 pods doing the most receive network traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, (sum by (pod_name) (irate(container_network_receive_bytes_total[5m]))))"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "kubelet_pleg_relist",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "kubelet_pleg_relist_latency_microseconds"
      }
     ]
    },
    {
     "title": "kubelet_docker_operations_latency_microseconds{quantile=\"0.9\"}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "kubelet_docker_operations_latency_microseconds{quantile=\"0.9\"}"
      }
     ]
    },
    {
     "title": "Returns a running count (not a rate) of docker operations that have timed out since the kubelet was started.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kubelet_docker_operations_timeout"
      }
     ]
    },
    {
     "title": "Returns a running count (not a rate) of docker operations that have failed since the kubelet was started.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kubelet_docker_operations_errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "scrape_samples_scraped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "scrape_samples_scraped" }
     ]
    },
    {
     "title": "CPU per instance of Prometheus container.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "drop_common_labels(sort_desc(sum without (cpu) (irate(container_cpu_usage_seconds_total{container_name=\"prometheus\"}[5m]))))"
      }
     ]
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Number of mutating API requests being made to the control plane.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(drop_common_labels(sum without (instance,type,client,contentType) (irate(apiserver_request_count{verb!~\"GET|LIST|WATCH\"}[2m])))) > 0"
    }
   ]
  },
  {
   "title": "Number of non-mutating API requests being made to the control plane.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(drop_common_labels(sum without (instance,type,client,contentType) (irate(apiserver_request_count{verb=~\"GET|LIST|WATCH\"}[2m])))) > 0"
    }
   ]
  },
  {
   "title": "endpoint_queue_latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "endpoint_queue_latency" }
   ]
  },
  {
   "title": "etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "etcd_disk_wal_fsync_duration_seconds_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "etcd_disk_wal_fsync_duration_seconds_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Changes in your cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "The number of containers that start or restart over the last ten minutes.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(changes(container_start_time_seconds[10m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "System and container CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of cores in the cluster.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "sum(machine_cpu_cores)" }
     ]
    },
    {
     "title": "Total number of consumed cores.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(sort_desc(irate(container_cpu_usage_seconds_total{id=\"/\"}[5m])))"
      }
     ]
    },
    {
     "title": "CPU consumed per node in the cluster.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (kubernetes_io_hostname,type) (irate(container_cpu_usage_seconds_total{id=\"/\"}[5m])))"
      }
     ]
    },
    {
     "title": "CPU consumption per system service or container on the infrastructure nodes.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (cpu,id,pod_name,container_name) (irate(container_cpu_usage_seconds_total{region=\"infra\"}[5m])))"
      }
     ]
    },
    {
     "title": "CPU consumed per namespace on the cluster.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (irate(container_cpu_usage_seconds_total[5m])))"
      }
     ]
    },
    {
     "title": "Percentage of total cluster CPU in use",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[3m])) / sum(machine_cpu_cores)"
      }
     ]
    },
    {
     "title": "Percentage of total cluster memory in use",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss) / sum(machine_memory_bytes)"
      }
     ]
    },
    {
     "title": "Aggregate CPU usage (seconds total) of etcd+docker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (irate(container_cpu_usage_seconds_total{id=~\"/system.slice/(docker|etcd).service\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenShift Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "volumes_queue_latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "volumes_queue_latency" }
     ]
    },
    {
     "title": "cloudprovider_aws_api_request_duration_seconds_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cloudprovider_aws_api_request_duration_seconds_count"
      }
     ]
    },
    {
     "title": "storage_operation_duration_seconds_sum",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "storage_operation_duration_seconds_sum"
      }
     ]
    }
   ]
  }
 ]
}